import type { Company } from "@/types";

// クライアント企業10社のダミーデータ
// REQUIREMENTS.md セクション9.2 を参照
export const DUMMY_CLIENTS: Company[] = [
  {
    id: "c001",
    type: "client",
    name: "株式会社サンライト精機",
    industry: "manufacturing",
    employeeCount: 180,
    employeeScale: "sme",
    prefecture: "東京都",
    description:
      "産業機械の精密部品メーカー。エンジニア採用が進まず開発体制の強化が急務。",
    challenges: ["hr_recruitment"],
    budget: "budget_50k_100k",
    urgency: "within_1m",
    createdAt: "2024-04-10T00:00:00Z",
  },
  {
    id: "c002",
    type: "client",
    name: "中央フードマート株式会社",
    industry: "retail",
    employeeCount: 320,
    employeeScale: "mid",
    prefecture: "神奈川県",
    description:
      "首都圏で展開する食品スーパー。店舗のDX化と在庫管理効率化を推進中。",
    challenges: ["dx_promotion", "cost_reduction"],
    budget: "budget_50k_100k",
    urgency: "within_3m",
    createdAt: "2024-04-12T00:00:00Z",
  },
  {
    id: "c003",
    type: "client",
    name: "株式会社グランドビルド",
    industry: "construction",
    employeeCount: 95,
    employeeScale: "sme",
    prefecture: "千葉県",
    description: "中堅ゼネコン。若手の定着率改善と採用ブランディングが課題。",
    challenges: ["hr_retention", "hr_recruitment"],
    budget: "budget_10k_50k",
    urgency: "immediate",
    createdAt: "2024-04-15T00:00:00Z",
  },
  {
    id: "c004",
    type: "client",
    name: "医療法人ハーモニア",
    industry: "medical",
    employeeCount: 210,
    employeeScale: "sme",
    prefecture: "京都府",
    description: "総合クリニック。スタッフ定着と人事評価制度の見直しが急務。",
    challenges: ["hr_retention"],
    budget: "budget_10k_50k",
    urgency: "within_1m",
    createdAt: "2024-04-18T00:00:00Z",
  },
  {
    id: "c005",
    type: "client",
    name: "株式会社テックスマート",
    industry: "it",
    employeeCount: 55,
    employeeScale: "sme",
    prefecture: "東京都",
    description:
      "BtoB SaaSスタートアップ。インサイドセールス組織の立ち上げを急ぐ。",
    challenges: ["sales_strengthening"],
    budget: "budget_50k_100k",
    urgency: "immediate",
    createdAt: "2024-04-20T00:00:00Z",
  },
  {
    id: "c006",
    type: "client",
    name: "みなとみらい商事株式会社",
    industry: "wholesale",
    employeeCount: 140,
    employeeScale: "sme",
    prefecture: "神奈川県",
    description: "総合卸商社。営業DXによる既存顧客との接点強化を計画中。",
    challenges: ["sales_strengthening", "dx_promotion"],
    budget: "budget_50k_100k",
    urgency: "within_3m",
    createdAt: "2024-04-22T00:00:00Z",
  },
  {
    id: "c007",
    type: "client",
    name: "東和ホールディングス",
    industry: "realestate",
    employeeCount: 78,
    employeeScale: "sme",
    prefecture: "東京都",
    description: "不動産開発会社。M&A戦略および資金調達の相談先を探している。",
    challenges: ["finance_funding", "management_consulting"],
    budget: "budget_over_100k",
    urgency: "within_3m",
    createdAt: "2024-04-25T00:00:00Z",
  },
  {
    id: "c008",
    type: "client",
    name: "株式会社プレシャス・コア",
    industry: "manufacturing",
    employeeCount: 230,
    employeeScale: "sme",
    prefecture: "大阪府",
    description: "化学素材メーカー。間接費削減と購買改革プロジェクトを始動。",
    challenges: ["cost_reduction"],
    budget: "budget_50k_100k",
    urgency: "within_1m",
    createdAt: "2024-04-26T00:00:00Z",
  },
  {
    id: "c009",
    type: "client",
    name: "関西ロジスティクス株式会社",
    industry: "logistics",
    employeeCount: 160,
    employeeScale: "sme",
    prefecture: "大阪府",
    description: "西日本中心の物流会社。物流DX・配送効率化を推進。",
    challenges: ["dx_promotion", "it_infrastructure"],
    budget: "budget_over_100k",
    urgency: "within_3m",
    createdAt: "2024-04-27T00:00:00Z",
  },
  {
    id: "c010",
    type: "client",
    name: "株式会社ナチュラルパス",
    industry: "service",
    employeeCount: 42,
    employeeScale: "small",
    prefecture: "東京都",
    description: "美容・健康ブランド。BtoBマーケと新規開拓を強化したい。",
    challenges: ["marketing", "sales_strengthening"],
    budget: "budget_10k_50k",
    urgency: "within_1m",
    createdAt: "2024-04-28T00:00:00Z",
  },
];

export function findClientById(id: string): Company | undefined {
  return DUMMY_CLIENTS.find((c) => c.id === id);
}
