import type { Company } from "@/types";

// 支援先企業20社のダミーデータ
// REQUIREMENTS.md セクション9.1 を参照
export const DUMMY_SUPPLIERS: Company[] = [
  {
    id: "s001",
    type: "supplier",
    name: "株式会社ピープルブリッジ",
    industry: "service",
    employeeCount: 45,
    employeeScale: "small",
    prefecture: "東京都",
    description:
      "エンジニア採用支援とスカウト代行に特化。IT・SaaS企業を中心に200社以上の採用実績。",
    serviceCategories: ["hr_recruitment"],
    targetIndustries: ["it", "manufacturing", "service"],
    targetScales: ["small", "sme", "mid"],
    targetAreas: ["全国"],
    priceRangeMin: 300000,
    meetingPriority: "high",
    responseRate: 0.78,
    successCount: 24,
    totalOffers: 32,
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "s002",
    type: "supplier",
    name: "合同会社デジタルパス",
    industry: "it",
    employeeCount: 28,
    employeeScale: "small",
    prefecture: "東京都",
    description:
      "中小企業向けDX伴走支援。SaaS導入・業務プロセス改革を伴走型で支援。",
    serviceCategories: ["dx_promotion", "it_infrastructure"],
    targetIndustries: ["manufacturing", "retail", "wholesale", "service"],
    targetScales: ["small", "sme"],
    targetAreas: ["東京都", "神奈川県", "千葉県", "埼玉県"],
    priceRangeMin: 200000,
    meetingPriority: "high",
    responseRate: 0.85,
    successCount: 18,
    totalOffers: 22,
    createdAt: "2024-02-05T00:00:00Z",
  },
  {
    id: "s003",
    type: "supplier",
    name: "株式会社グロースセイル",
    industry: "service",
    employeeCount: 120,
    employeeScale: "sme",
    prefecture: "東京都",
    description:
      "BtoBインサイドセールス代行。リード獲得から商談化までワンストップで支援。",
    serviceCategories: ["sales_strengthening", "marketing"],
    targetIndustries: ["it", "manufacturing", "service", "wholesale"],
    targetScales: ["sme", "mid"],
    targetAreas: ["全国"],
    priceRangeMin: 500000,
    meetingPriority: "medium",
    responseRate: 0.62,
    successCount: 28,
    totalOffers: 45,
    createdAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "s004",
    type: "supplier",
    name: "株式会社マーケライズ",
    industry: "service",
    employeeCount: 35,
    employeeScale: "small",
    prefecture: "大阪府",
    description:
      "BtoBマーケティング戦略立案・MA(マーケティングオートメーション)運用支援。",
    serviceCategories: ["marketing", "sales_strengthening"],
    targetIndustries: ["it", "manufacturing", "service"],
    targetScales: ["small", "sme", "mid"],
    targetAreas: ["大阪府", "京都府", "兵庫県", "東京都"],
    priceRangeMin: 400000,
    meetingPriority: "medium",
    responseRate: 0.71,
    successCount: 16,
    totalOffers: 24,
    createdAt: "2024-03-12T00:00:00Z",
  },
  {
    id: "s005",
    type: "supplier",
    name: "合同会社レビュレント",
    industry: "finance",
    employeeCount: 15,
    employeeScale: "small",
    prefecture: "東京都",
    description:
      "間接費削減コンサルティング。購買改革・コスト最適化のプロフェッショナル。",
    serviceCategories: ["cost_reduction"],
    targetIndustries: ["manufacturing", "retail", "wholesale", "construction"],
    targetScales: ["sme", "mid", "large"],
    targetAreas: ["全国"],
    priceRangeMin: 300000,
    meetingPriority: "medium",
    responseRate: 0.68,
    successCount: 12,
    totalOffers: 19,
    createdAt: "2024-02-18T00:00:00Z",
  },
  {
    id: "s006",
    type: "supplier",
    name: "株式会社シナジクト",
    industry: "service",
    employeeCount: 60,
    employeeScale: "sme",
    prefecture: "東京都",
    description:
      "中堅企業向け経営戦略コンサルティング。事業計画・組織変革を支援。",
    serviceCategories: ["management_consulting"],
    targetIndustries: ["manufacturing", "service", "retail", "construction"],
    targetScales: ["sme", "mid"],
    targetAreas: ["全国"],
    priceRangeMin: 800000,
    meetingPriority: "low",
    responseRate: 0.45,
    successCount: 8,
    totalOffers: 18,
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "s007",
    type: "supplier",
    name: "株式会社プラットIT",
    industry: "it",
    employeeCount: 85,
    employeeScale: "sme",
    prefecture: "愛知県",
    description: "クラウド移行・セキュリティ強化に強み。中部エリア中心に支援。",
    serviceCategories: ["it_infrastructure", "dx_promotion"],
    targetIndustries: ["manufacturing", "service", "logistics"],
    targetScales: ["sme", "mid", "large"],
    targetAreas: ["愛知県", "岐阜県", "三重県", "静岡県"],
    priceRangeMin: 500000,
    meetingPriority: "medium",
    responseRate: 0.66,
    successCount: 14,
    totalOffers: 21,
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "s008",
    type: "supplier",
    name: "弁護士法人ライトリー",
    industry: "service",
    employeeCount: 25,
    employeeScale: "small",
    prefecture: "東京都",
    description:
      "中小企業向け法務顧問・契約書レビュー。ITサービス契約・利用規約作成に強み。",
    serviceCategories: ["legal_compliance"],
    targetIndustries: ["it", "service", "retail"],
    targetScales: ["micro", "small", "sme"],
    targetAreas: ["全国"],
    priceRangeMin: 100000,
    meetingPriority: "high",
    responseRate: 0.82,
    successCount: 21,
    totalOffers: 26,
    createdAt: "2024-02-22T00:00:00Z",
  },
  {
    id: "s009",
    type: "supplier",
    name: "株式会社ファンドリンク",
    industry: "finance",
    employeeCount: 18,
    employeeScale: "small",
    prefecture: "東京都",
    description:
      "ベンチャー融資・補助金申請支援。スタートアップから中堅まで幅広く対応。",
    serviceCategories: ["finance_funding"],
    targetIndustries: ["it", "service", "manufacturing", "realestate"],
    targetScales: ["micro", "small", "sme", "mid"],
    targetAreas: ["全国"],
    priceRangeMin: 150000,
    meetingPriority: "high",
    responseRate: 0.74,
    successCount: 19,
    totalOffers: 27,
    createdAt: "2024-01-25T00:00:00Z",
  },
  {
    id: "s010",
    type: "supplier",
    name: "株式会社オフィスエア",
    industry: "service",
    employeeCount: 40,
    employeeScale: "small",
    prefecture: "東京都",
    description: "評価制度設計・組織開発支援。人事評価運用の伴走支援に強み。",
    serviceCategories: ["hr_retention", "management_consulting"],
    targetIndustries: ["service", "it", "manufacturing", "medical"],
    targetScales: ["small", "sme", "mid"],
    targetAreas: ["全国"],
    priceRangeMin: 400000,
    meetingPriority: "medium",
    responseRate: 0.7,
    successCount: 17,
    totalOffers: 25,
    createdAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "s011",
    type: "supplier",
    name: "株式会社ブランドルート",
    industry: "service",
    employeeCount: 22,
    employeeScale: "small",
    prefecture: "東京都",
    description:
      "BtoB企業のブランド再構築・コーポレートブランディング。製造業実績多数。",
    serviceCategories: ["marketing"],
    targetIndustries: ["manufacturing", "service", "wholesale"],
    targetScales: ["sme", "mid"],
    targetAreas: ["東京都", "神奈川県"],
    priceRangeMin: 600000,
    meetingPriority: "low",
    responseRate: 0.42,
    successCount: 9,
    totalOffers: 21,
    createdAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "s012",
    type: "supplier",
    name: "株式会社チームブースト",
    industry: "service",
    employeeCount: 55,
    employeeScale: "sme",
    prefecture: "神奈川県",
    description:
      "1on1導入・エンゲージメント向上支援。組織サーベイから改善まで一気通貫。",
    serviceCategories: ["hr_retention"],
    targetIndustries: ["service", "manufacturing", "it", "construction"],
    targetScales: ["sme", "mid"],
    targetAreas: ["全国"],
    priceRangeMin: 300000,
    meetingPriority: "high",
    responseRate: 0.76,
    successCount: 22,
    totalOffers: 29,
    createdAt: "2024-01-30T00:00:00Z",
  },
  {
    id: "s013",
    type: "supplier",
    name: "合同会社プロメソッド",
    industry: "it",
    employeeCount: 30,
    employeeScale: "small",
    prefecture: "東京都",
    description: "基幹システム刷新・PMO支援。中堅製造業のSAP導入実績多数。",
    serviceCategories: ["it_infrastructure", "dx_promotion"],
    targetIndustries: ["manufacturing", "wholesale", "logistics"],
    targetScales: ["mid", "large"],
    targetAreas: ["全国"],
    priceRangeMin: 1200000,
    meetingPriority: "low",
    responseRate: 0.38,
    successCount: 7,
    totalOffers: 18,
    createdAt: "2024-02-28T00:00:00Z",
  },
  {
    id: "s014",
    type: "supplier",
    name: "株式会社セールスバニッシュ",
    industry: "service",
    employeeCount: 70,
    employeeScale: "sme",
    prefecture: "福岡県",
    description: "営業DX・SFA(Salesforce)導入伴走支援。九州エリア最大手。",
    serviceCategories: ["sales_strengthening", "dx_promotion"],
    targetIndustries: ["it", "manufacturing", "service", "wholesale"],
    targetScales: ["sme", "mid"],
    targetAreas: ["福岡県", "熊本県", "大分県", "佐賀県", "全国"],
    priceRangeMin: 500000,
    meetingPriority: "high",
    responseRate: 0.79,
    successCount: 26,
    totalOffers: 33,
    createdAt: "2024-01-18T00:00:00Z",
  },
  {
    id: "s015",
    type: "supplier",
    name: "株式会社マターズ",
    industry: "service",
    employeeCount: 12,
    employeeScale: "small",
    prefecture: "東京都",
    description:
      "スタートアップ法務・IPO準備支援。シリーズA〜上場前まで一気通貫対応。",
    serviceCategories: ["legal_compliance", "finance_funding"],
    targetIndustries: ["it", "service"],
    targetScales: ["micro", "small", "sme"],
    targetAreas: ["全国"],
    priceRangeMin: 200000,
    meetingPriority: "medium",
    responseRate: 0.6,
    successCount: 11,
    totalOffers: 19,
    createdAt: "2024-03-08T00:00:00Z",
  },
  {
    id: "s016",
    type: "supplier",
    name: "株式会社ハーモニーHR",
    industry: "service",
    employeeCount: 38,
    employeeScale: "small",
    prefecture: "京都府",
    description: "リファラル採用・ATS導入支援。関西エリアの中堅企業に強み。",
    serviceCategories: ["hr_recruitment", "hr_retention"],
    targetIndustries: ["service", "manufacturing", "retail", "medical"],
    targetScales: ["sme", "mid"],
    targetAreas: ["京都府", "大阪府", "兵庫県", "滋賀県"],
    priceRangeMin: 250000,
    meetingPriority: "high",
    responseRate: 0.73,
    successCount: 15,
    totalOffers: 22,
    createdAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "s017",
    type: "supplier",
    name: "合同会社デザインラフト",
    industry: "service",
    employeeCount: 20,
    employeeScale: "small",
    prefecture: "東京都",
    description: "UI/UXデザイン・コーポレートサイト制作。BtoBスタートアップ実績多数。",
    serviceCategories: ["marketing"],
    targetIndustries: ["it", "service"],
    targetScales: ["micro", "small", "sme"],
    targetAreas: ["全国"],
    priceRangeMin: 200000,
    meetingPriority: "medium",
    responseRate: 0.65,
    successCount: 13,
    totalOffers: 22,
    createdAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "s018",
    type: "supplier",
    name: "株式会社ロジテック",
    industry: "it",
    employeeCount: 95,
    employeeScale: "sme",
    prefecture: "大阪府",
    description: "物流業界向けシステム開発・WMS導入。倉庫管理DXに圧倒的実績。",
    serviceCategories: ["dx_promotion", "it_infrastructure"],
    targetIndustries: ["logistics", "wholesale", "manufacturing"],
    targetScales: ["sme", "mid", "large"],
    targetAreas: ["全国"],
    priceRangeMin: 800000,
    meetingPriority: "medium",
    responseRate: 0.58,
    successCount: 16,
    totalOffers: 27,
    createdAt: "2024-01-22T00:00:00Z",
  },
  {
    id: "s019",
    type: "supplier",
    name: "株式会社ゼロアウト",
    industry: "service",
    employeeCount: 28,
    employeeScale: "small",
    prefecture: "東京都",
    description: "通信費・電力料金見直しコンサル。固定費削減1000社実績。",
    serviceCategories: ["cost_reduction"],
    targetIndustries: ["retail", "service", "manufacturing", "medical"],
    targetScales: ["small", "sme", "mid"],
    targetAreas: ["全国"],
    priceRangeMin: 50000,
    meetingPriority: "high",
    responseRate: 0.88,
    successCount: 30,
    totalOffers: 35,
    createdAt: "2024-02-08T00:00:00Z",
  },
  {
    id: "s020",
    type: "supplier",
    name: "株式会社ヒトイチ",
    industry: "service",
    employeeCount: 48,
    employeeScale: "small",
    prefecture: "兵庫県",
    description: "リーダー育成研修・1on1コーチング。製造業の管理職育成に定評。",
    serviceCategories: ["hr_retention", "management_consulting"],
    targetIndustries: ["manufacturing", "construction", "service"],
    targetScales: ["sme", "mid"],
    targetAreas: ["兵庫県", "大阪府", "京都府", "全国"],
    priceRangeMin: 350000,
    meetingPriority: "medium",
    responseRate: 0.69,
    successCount: 14,
    totalOffers: 22,
    createdAt: "2024-03-05T00:00:00Z",
  },
];

export function findSupplierById(id: string): Company | undefined {
  return DUMMY_SUPPLIERS.find((s) => s.id === id);
}
